# site settings
title: The MINT - Rutland's Makerspace
description: "The MINT is a Makerspace in Rutland, Vermont."
future: true

# build settings
port: 4000

collections:
  wishlist:
    output: false