# site settings
title: The MINT - Rutland's Makerspace
description: "The MINT is a Makerspace in Rutland, Vermont."
future: true

# build settings
port: 4000
host: 0.0.0.0

collections:
  wishlist:
    output: false
    
sass:
  sass_dir: _sass
#  style: compressed